name: Plex Media Server
description: Plex organizes your video, music, and photo collections and streams them to all of your screens.
category: Organize
version: 1.0
maintainer: Jason Kulatunga <jason@thesparktree.com>
license: MIT
projectURL: https://github.com/mediadepot/docker-plex