name: PlexPy
description: A Python based monitoring and tracking tool for Plex Media Server.
category: Utility
version: 1.0
maintainer: Jason Kulatunga <jason@thesparktree.com>
license: MIT
projectURL: https://github.com/mediadepot/docker-plexpy