app:
  restart: always
  image: mediadepot/lazylibrarian:master
  ports:
   - "5299"
  volumes_from:
  - data
  volumes:
  - /media/storage/ebooks:/mnt/ebooks
  - /media/storage/downloads/ebooks:/mnt/downloads
  - /media/temp/blackhole/ebooks:/mnt/blackhole
  labels:
    io.rancher.sidekicks: data
    depot.lb.link: true
    depot.lb.port: 5299
    depot.app.type: lazylibrarian
data:
  image: tianon/true
  labels:
    io.rancher.container.start_once: true
  volumes:
  - /srv/lazylibrarian/config
  - /srv/lazylibrarian/data