version: '2'
services:
  app:
    restart: always
    image: mediadepot/lazylibrarian:master
    ports:
     - "5299"
    volumes_from:
    - data
    volumes:
    - /media/storage/ebooks:/mnt/ebooks
    - /media/storage/downloads/ebooks:/mnt/downloads
    - /media/temp/blackhole/ebooks:/mnt/blackhole
    - ${CONFIG_DIRECTORY}:/srv/lazylibrarian/config
    labels:
      io.rancher.sidekicks: data
      depot.lb.link: true
      depot.app.type: lazylibrarian
  data:
    image: tianon/true
    labels:
      io.rancher.container.start_once: true
    volumes:
    - /srv/lazylibrarian/data