app:
  restart: always
  image: mediadepot/madsonic:master
  ports:
   - "8080"
  volumes_from:
  - data
  volumes:
  - /media/storage/music:/mnt/music
  - /media/storage/downloads/music:/mnt/downloads
  - /media/temp/blackhole/music:/mnt/blackhole
  labels:
    io.rancher.sidekicks: data
    depot.lb.link: true
    depot.lb.port: 8080
    depot.app.type: madsonic
data:
  image: tianon/true
  labels:
    io.rancher.container.start_once: true
  volumes:
  - /srv/madsonic/config
  - /srv/madsonic/data