version: '2'
services:
  app:
    restart: always
    image: mediadepot/urlwatch:master
    ports:
     - "8081"
    volumes_from:
    - data
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - ${CONFIG_DIRECTORY}:/srv/urlwatch/config

    labels:
      io.rancher.container.pull_image: always
      io.rancher.sidekicks: data
      depot.lb.link: true
      depot.app.type: urlwatch
  data:
    image: tianon/true
    labels:
      io.rancher.container.start_once: true
    volumes:
    - /srv/urlwatch/data