name: Stremio
description: Stremio is an app that helps you organize and instantly watch your favorite videos, movies, TV series and TV channels.
category: Organize
version: 1.0
maintainer: Jason Kulatunga <jason@thesparktree.com>
license: MIT
projectURL: https://github.com/mediadepot/docker-stremio