version: '2'
services:
  app:
    restart: always
    image: mediadepot/rtorrent:master
    ports:
     - "8081"
     - "6880"
     - "6881"
     - "6882"
     - "6883"
     - "6884"
     - "6885"
     - "6886"
     - "6887"
     - "6888"
     - "6889"
    volumes_from:
    - data
    volumes:
    - /media/temp/processing:/mnt/processing
    - /media/temp/blackhole:/mnt/blackhole
    - /media/storage/downloads:/mnt/downloads
    - ${CONFIG_DIRECTORY}:/srv/rtorrent/config
    labels:
      io.rancher.container.pull_image: always
      io.rancher.sidekicks: data
      depot.lb.link: true
      depot.app.type: rtorrent
    environment:
      DEPOT_USER: ${DEPOT_USER}
      DEPOT_PASSWORD: ${DEPOT_PASSWORD}
    network_mode: "host"
  data:
    image: tianon/true
    labels:
      io.rancher.container.start_once: true
    volumes:
    - /srv/rtorrent/data