version: '2'
catalog:
  name: "rtorrent"
  version: "1.0"
  description: "rTorrent and Flood"
  uuid: rtorrent-0
  questions:
    - variable: "DEPOT_USER"
      description: "The username to login to the application with"
      label: "Username"
      required: true
      default: "depot"
      type: "string"
    - variable: "DEPOT_PASSWORD"
      description: "The password to login to the application with"
      label: "Password"
      required: true
      default: "depotd3p0!"
      type: "string"
    - variable: "APP_HOSTNAME"
      description: "The public hostname for this app"
      label: "Rtorrent load balancer hostname"
      required: true
      default: "rtorrent.depot.lan"
      type: "string"
    - variable: "CONFIG_DIRECTORY"
      description: "The configuration directory for this app"
      label: "Configuration directory"
      required: true
      default: "/srv/apps/rtorrent"
      type: "string"
services:
  app:
    scale: 1
    lb_config:
      port_rules:
      - target_port: 8081
        hostname: $APP_HOSTNAME
    health_check:
      port: 8081
      interval: 2000
      unhealthy_threshold: 3
      healthy_threshold: 2
      response_timeout: 2000
  data:
    scale: 1