lb:
  image: rancher/load-balancer-service
  ports:
  # Listen on public port 80 and direct traffic to private port 80 of the service
  - 50001:80
  # links:
  # Target services in the same stack will be listed as a link
  #  - web1:web1a
  #  - web2:web2a
#  external_links:
#  # Target services in a different stack will be listed as an external link
#  - btsync/app:btsync
#  - couchpotato/app:couchpotato
#  - deluge/app:deluge
#  - guacamole/guacweb:guacweb
#  - headphones/app:headphones
#  - lazylibrarian/app:lazylibrarian
#  - plex/app:plex
#  - sickrage/app:sickrage
#  - syncthing/app:syncthing
  labels:
    io.rancher.service.selector.link: depot.lb.link
#    # Put load balancer containers on hosts with label lb=true
#    # io.rancher.scheduler.affinity:host_label: lb=true
#    # Requests to http://app.example.com/foo:80 should be routed to web1 over port 8000
#    io.rancher.loadbalancer.target.btsync/app: btsync.depot.local=8081
#    io.rancher.loadbalancer.target.couchpotato/app: couchpotato.depot.local=8081
#    io.rancher.loadbalancer.target.guacamole/guacweb: vpn.depot.local=8080
#    io.rancher.loadbalancer.target.headphones/app: headphones.depot.local=8081
#    io.rancher.loadbalancer.target.lazylibrarian/app: lazylibrarian.depot.local=8081
#    io.rancher.loadbalancer.target.plex/app: plex.depot.local=32400
#    io.rancher.loadbalancer.target.sickrage/app: sickrage.depot.local=8081
#    io.rancher.loadbalancer.target.syncthing/app: plex.depot.local=8081
