version: '2'
services:
  lb:
    image: rancher/lb-service-haproxy:v0.7.10
    ports:
    - 80
    - 6668:6668/tcp
    labels:
      io.rancher.container.agent.role: environmentAdmin
      io.rancher.container.create_agent: 'true'
      io.rancher.scheduler.global: 'true'
      loadbalancer: stats
  manager:
    image: rancher/external-service
