version: '2'
catalog:
  name: "plexpy"
  version: "1.0"
  description: "PlexPy"
  uuid: plexpy-0
  questions:
    - variable: "APP_HOSTNAME"
      description: "The public hostname for this app"
      label: "Plexpy load balancer hostname"
      required: true
      default: "plexpy.depot.lan"
      type: "string"
    - variable: "CONFIG_DIRECTORY"
      description: "The configuration directory for this app"
      label: "Configuration directory"
      required: true
      default: "/srv/apps/plexpy"
      type: "string"
services:
  app:
    scale: 1
    lb_config:
      port_rules:
      - target_port: 8181
        hostname: $APP_HOSTNAME
    health_check:
      port: 8181
      interval: 2000
      unhealthy_threshold: 3
      healthy_threshold: 2
      response_timeout: 2000
  data:
    scale: 1