app:
  restart: always
  image: mediadepot/couchpotato:master
  ports:
   - "5050"
  volumes_from:
  - data
  volumes:
  - /media/storage/movies:/mnt/movies
  - /media/storage/downloads/movies:/mnt/downloads
  - /media/temp/blackhole/movies:/mnt/blackhole
  labels:
    io.rancher.sidekicks: data
    depot.lb.link: true
    depot.lb.port: 5050
    depot.app.type: couchpotato
data:
  image: tianon/true
  labels:
    io.rancher.container.start_once: true
  volumes:
  - /srv/couchpotato/config
  - /srv/couchpotato/data