version: '2'
services:
  app:
    restart: always
    image: mediadepot/couchpotato:master
    ports:
     - "5050"
    volumes_from:
    - data
    volumes:
    - /media/storage/movies:/mnt/movies
    - /media/storage/downloads/movies:/mnt/downloads
    - /media/temp/blackhole/movies:/mnt/blackhole
    - ${CONFIG_DIRECTORY}:/srv/couchpotato/config
    labels:
      io.rancher.container.pull_image: always
      io.rancher.sidekicks: data
      depot.lb.link: true
      depot.app.type: couchpotato
  data:
    image: tianon/true
    labels:
      io.rancher.container.start_once: true
    volumes:
    - /srv/couchpotato/data