app:
  restart: always
  image: mediadepot/couchpotato:master
  ports:
   - "8081"
  volumes_from:
  - data
  volumes:
  - /mnt/samba/movies:/mnt/movies
  - /mnt/samba/downloads/[Movies]:/mnt/downloads
  - /mnt/samba/blackhole/[Movies]:/mnt/blackhole
  labels:
    io.rancher.sidekicks: data
    depot.lb.link: true
    depot.lb.port: 8081
  environment:
    DEPOT_USER: ${DEPOT_USER}
    DEPOT_PASSWORD: ${DEPOT_PASSWORD}
data:
  image: tianon/true
  labels:
    io.rancher.container.start_once: true
  volumes:
  - /srv/couchpotato/config
  - /srv/couchpotato/data