app:
  restart: always
  image: mediadepot/couchpotato:master
  ports:
   - "8081"
  volumes_from:
  - data
  volumes:
  - /mnt/samba/movies:/mnt/movies
  - /mnt/samba/downloads/[Movies]:/mnt/downloads
  - /mnt/samba/blackhole/[Movies]:/mnt/blackhole
  labels:
    io.rancher.sidekicks: data
    depot.lb.link: true
data:
  image: tianon/true
  volumes:
  - /srv/couchpotato/config
  - /srv/couchpotato/data