version: '2'
catalog:
  name: "couchpotato"
  version: "1.0"
  description: "Couchpotato"
  uuid: couchpotato-0
  questions:
    - variable: "APP_HOSTNAME"
      description: "The public hostname for this app"
      label: "Couchpotato load balancer hostname"
      required: true
      default: "couchpotato.depot.lan"
      type: "string"
    - variable: "CONFIG_DIRECTORY"
      description: "The configuration directory for this app"
      label: "Configuration directory"
      required: true
      default: "/srv/apps/couchpotato"
      type: "string"
services:
  app:
    scale: 1
    lb_config:
      port_rules:
      - target_port: 5050
        hostname: $APP_HOSTNAME
  data:
    scale: 1