version: '2'
catalog:
  name: "filerun"
  version: "1.0"
  description: "Filerun"
  uuid: filerun-0
  questions:
    - variable: "APP_HOSTNAME"
      description: "The public hostname for this app"
      label: "Filerun load balancer hostname"
      required: true
      default: "files.depot.lan"
      type: "string"
    - variable: "CONFIG_DIRECTORY"
      description: "The configuration directory for this app"
      label: "Configuration directory"
      required: true
      default: "/srv/apps/filerun"
      type: "string"
services:
  app:
    scale: 1
    lb_config:
      port_rules:
      - target_port: 80
        hostname: $APP_HOSTNAME
    health_check:
      port: 80
      interval: 2000
      unhealthy_threshold: 3
      healthy_threshold: 2
      response_timeout: 2000