app:
  restart: always
  image: mediadepot/deluge:master
  ports:
   - "8081"
   - "6881-6891"
  volumes_from:
  - data
  volumes:
  - /mnt/samba/processing:/mnt/processing
  - /mnt/samba/downloads:/mnt/downloads
  - /mnt/samba/blackhole:/mnt/blackhole
  labels:
    io.rancher.sidekicks: data
    depot.lb.link: true
data:
  image: tianon/true
  labels:
    io.rancher.container.start_once: true
  volumes:
  - /srv/deluge/config
  - /srv/deluge/data