version: '2'
services:
  app:
    restart: always
    image: mediadepot/deluge:master
    ports:
     - "8081"
     - "6881"
     - "6882"
     - "6883"
     - "6884"
     - "6885"
     - "6886"
     - "6887"
     - "6888"
     - "6889"
    volumes_from:
    - data
    volumes:
    - /media/temp/processing:/mnt/processing
    - /media/temp/blackhole:/mnt/blackhole
    - /media/storage/downloads:/mnt/downloads
    - ${CONFIG_DIRECTORY}:/srv/deluge/config
    labels:
      io.rancher.container.pull_image: always
      io.rancher.sidekicks: data
      depot.lb.link: true
      depot.app.type: deluge
    environment:
      DEPOT_USER: ${DEPOT_USER}
      DEPOT_PASSWORD: ${DEPOT_PASSWORD}
      DELUGE_PASSWORD_SALT: 12345
      PUSHOVER_USER_KEY:
  data:
    image: tianon/true
    labels:
      io.rancher.container.start_once: true
    volumes:
    - /srv/deluge/data