name: Deluge
description: Open source, cross-platform BitTorrent client.
category: Download
version: 1.0
maintainer: Jason Kulatunga <jason@thesparktree.com>
license: MIT
projectURL: https://github.com/mediadepot/docker-deluge