version: '2'
services:
  app:
    restart: always
    image: mediadepot/btsync:master
    ports:
     - "8888"
     - "55555:55555"
    volumes_from:
    - data
    volumes:
    - /media/storage/tvshows:/mnt/tvshows
    - /media/storage/movies:/mnt/movies
    - /media/storage/music:/mnt/music
    - /media/storage/photos:/mnt/photos
    - /media/storage/ebooks:/mnt/ebooks
    - /media/temp/blackhole:/mnt/blackhole
    - ${CONFIG_DIRECTORY}:/srv/btsync/config
    labels:
      io.rancher.container.pull_image: always
      io.rancher.sidekicks: data
      depot.lb.link: true
      depot.app.type: btsync
    environment:
      - DEPOT_USER
      - DEPOT_PASSWORD
  data:
    image: tianon/true
    labels:
      io.rancher.container.start_once: true
    volumes:
    - /srv/btsync/data