app:
  restart: always
  image: mediadepot/btsync:master
  ports:
   - "8080"
   - "55555:55555"
  volumes_from:
  - data
  volumes:
  - /media/storage/[Tvshows]:/mnt/tvshows
  - /media/storage/[Movies]:/mnt/movies
  - /media/storage/[Music]:/mnt/music
  - /media/storage/[Photos]:/mnt/photos
  - /media/storage/[Ebooks]:/mnt/ebooks
  - /media/temp/blackhole:/mnt/blackhole
  labels:
    io.rancher.sidekicks: data
    depot.lb.link: true
    depot.lb.port: 8080
    depot.app.type: btsync
data:
  image: tianon/true
  labels:
    io.rancher.container.start_once: true
  volumes:
  - /srv/btsync/config
  - /srv/btsync/data