.catalog:
  name: "btsync"
  version: "1.0"
  description: "Bittorrent Sync"
  uuid: btsync-0
  questions:
    - variable: "DEPOT_USER"
      description: "The username to login to the application with"
      label: "Username"
      required: true
      default: ${DEPOT_USER}
      type: "string"
    - variable: "DEPOT_PASSWORD"
      description: "The password to login to the application with"
      label: "Password"
      required: true
      default: ${DEPOT_PASSWORD}
      type: "string"
app:
  scale: 1
data:
  scale: 1