app:
  restart: always
  image: mediadepot/headphones:master
  ports:
   - "8181"
  volumes_from:
  - data
  volumes:
  - /media/storage/music:/mnt/music
  - /media/storage/downloads/music:/mnt/downloads
  - /media/temp/blackhole/music:/mnt/blackhole
  labels:
    io.rancher.sidekicks: data
    depot.lb.link: true
    depot.lb.port: 8181
    depot.app.type: headphones
data:
  image: tianon/true
  labels:
    io.rancher.container.start_once: true
  volumes:
  - /srv/headphones/config
  - /srv/headphones/data