app:
  restart: always
  image: mediadepot/headphones:master
  ports:
   - "8081"
  volumes_from:
  - data
  volumes:
  - /mnt/samba/music:/mnt/music
  - /mnt/samba/downloads/[Music]:/mnt/downloads
  - /mnt/samba/blackhole/[Music]:/mnt/blackhole
  labels:
    io.rancher.sidekicks: data
    depot.lb.link: true
    depot.lb.port: 8081
  environment:
    DEPOT_USER: ${DEPOT_USER}
    DEPOT_PASSWORD: ${DEPOT_PASSWORD}
    HEADPHONES_API_KEY:
    PUSHOVER_USER_KEY:
data:
  image: tianon/true
  labels:
    io.rancher.container.start_once: true
  volumes:
  - /srv/headphones/config
  - /srv/headphones/data