app:
  restart: always
  image: mediadepot/headphones:master
  ports:
   - "8081"
  volumes_from:
  - data
  volumes:
  - /media/storage/[Music]:/mnt/music
  - /media/storage/downloads/[Music]:/mnt/downloads
  - /media/temp/blackhole/[Music]:/mnt/blackhole
  labels:
    io.rancher.sidekicks: data
    depot.lb.link: true
    depot.lb.port: 8081
    depot.app.type: headphones
data:
  image: tianon/true
  labels:
    io.rancher.container.start_once: true
  volumes:
  - /srv/headphones/config
  - /srv/headphones/data