version: '2'
services:
  app:
    restart: always
    image: mediadepot/headphones:master
    ports:
     - "8181"
    volumes_from:
    - data
    volumes:
    - /media/storage/music:/mnt/music
    - /media/storage/downloads/music:/mnt/downloads
    - /media/temp/blackhole/music:/mnt/blackhole
    - ${CONFIG_DIRECTORY}:/srv/headphones/config
    labels:
      io.rancher.container.pull_image: always
      io.rancher.sidekicks: data
      depot.lb.link: true
      depot.app.type: headphones
  data:
    image: tianon/true
    labels:
      io.rancher.container.start_once: true
    volumes:
    - /srv/headphones/data