version: '2'
catalog:
  name: "plexrequests"
  version: "1.0"
  description: "Plex Requests"
  uuid: plexrequests-0
  questions:
    - variable: "APP_HOSTNAME"
      description: "The public hostname for this app"
      label: "Plex Requests load balancer hostname"
      required: true
      default: "plexrequests.depot.lan"
      type: "string"
    - variable: "CONFIG_DIRECTORY"
      description: "The configuration directory for this app"
      label: "Configuration directory"
      required: true
      default: "/srv/apps/plexrequests"
      type: "string"
services:
  app:
    scale: 1
    lb_config:
      port_rules:
      - target_port: 3000
        hostname: $APP_HOSTNAME
  data:
    scale: 1