name: Backup Library Config
description: Backup your library metadata content to github
category: Utility
version: 1.0
maintainer: Jason Kulatunga <jason@thesparktree.com>
license: MIT
projectURL: https://github.com/mediadepot/rancher-catalog