guacd:
  image: mattgruter/guacamole-guacd
db:
  image: mattgruter/guacamole-db
guacweb:
  image: mattgruter/guacamole-webserver
  links:
    - guacd
    - db
  ports:
    - "8080"
  labels:
    depot.lb.link: true
    depot.lb.port: 8080