version: '2'
services:
  guacd:
    image: mattgruter/guacamole-guacd
  guacweb:
    image: mediadepot/guacamole-webserver
    links:
      - guacd
    ports:
      - "8080"
    labels:
      depot.lb.link: true
      depot.app.type: guacamole
    volumes:
    - ${CONFIG_DIRECTORY}:/srv/guacamole/config
