guacd:
  image: mattgruter/guacamole-guacd
guacweb:
  image: mediadepot/guacamole-webserver
  links:
    - guacd
  ports:
    - "8080"
  labels:
    depot.lb.link: true
    depot.lb.port: 8080
  environment:
    DEPOT_USER: ${DEPOT_USER}
    DEPOT_PASSWORD: ${DEPOT_PASSWORD}
data:
  image: tianon/true
  labels:
    io.rancher.container.start_once: true
  volumes:
  - /srv/guacamole/config