guacd:
  image: mattgruter/guacamole-guacd
db:
  image: mattgruter/guacamole-db
guacweb:
  image: mediadepot/guacamole-webserver
  links:
    - guacd
    - db
  ports:
    - "8081"
  labels:
    depot.lb.link: true
    depot.lb.port: 8081
  environment:
    DEPOT_USER: ${DEPOT_USER}
    DEPOT_PASSWORD: ${DEPOT_PASSWORD}
    DEPOT_HOST:
data:
  image: tianon/true
  labels:
    io.rancher.container.start_once: true
  volumes:
  - /srv/guacamole/config